baseURL = 'https://spencergreenhalgh.com/'
languageCode = 'en-us'
title = 'Spencer Greenhalgh'
theme = "ananke_custom_2023"
# themesDir = "../.."
# resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 36 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false
capitalizeListTitles = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Spencer Greenhalgh"
  text_color = ""
  author = ""
  favicon = "/SPG_4_circle_small.png"
  site_logo = "/SPG_4_circle_small.png"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = ""
  recent_posts_number = 2


[[menu.main]]
  identifier = "CV"
  name = "CV"
  url = "/CV/"
  weight = 5
[[menu.main]]
  identifier = "How to Follow"
  name = "How to Follow"
  url = "/how-to-follow/"
  weight = 6





