baseURL = 'https://spencergreenhalgh.com/'
# languageCode = 'en-us'
title = 'Spencer Greenhalgh'
theme = "ananke_custom_2023"
# themesDir = "../.."
# resourceDir = "../resources"

DefaultContentLanguage = "en"
# SectionPagesMenu = "main"

googleAnalytics = ""
enableRobotsTXT = false
capitalizeListTitles = false

[pagination]
    pagerSize = 25

[languages]
    [languages.en]
       disabled = false
        languageCode = 'en'
        languageDirection = 'ltr'
        languageName = '[en]'
        weight = 1
        [languages.en.menus]
            [[languages.en.menus.main]]
                identifier = "Myself"
                name = "Myself"
                url = "/myself/"
                weight = 1  
            [[languages.en.menus.main]]
                identifier = "Relationships"
                name = "Relationships"
                url = "/relationships/"
                weight = 2    
            [[languages.en.menus.main]]
                identifier = "Work"
                name = "Work"
                url = "/work/"
                weight = 3    
            [[languages.en.menus.main]]
                identifier = "Communities"
                name = "Communities"
                url = "/communities/"
                weight = 4    
            [[languages.en.menus.main]]
                identifier = "CV"
                name = "CV"
                url = "/CV/"
                weight = 5   
            [[languages.en.menus.main]]
                identifier = "Research"
                name = "Research"
                url = "/research/"
                weight = 6       


    [languages.fr]
        disabled = false
        languageCode = 'fr'
        languageDirection = 'ltr'
        languageName = '[fr]'
        weight = 2
        [languages.fr.menus]
            [[languages.fr.menus.main]]
                identifier = "Moi"
                name = "Moi"
                url = "/fr/moi/"
                weight = 1  
            [[languages.fr.menus.main]]
                identifier = "Relations"
                name = "Relations"
                url = "/fr/relations/"
                weight = 2    
            [[languages.fr.menus.main]]
                identifier = "Travail"
                name = "Travail"
                url = "/fr/travail/"
                weight = 3    
            [[languages.fr.menus.main]]
                identifier = "Communautés"
                name = "Communautés"
                url = "/fr/communautes/"
                weight = 4    
            [[languages.fr.menus.main]]
                identifier = "CV"
                name = "CV"
                url = "/CV/"
                weight = 5    
            [[languages.fr.menus.main]]
                identifier = "Recherches"
                name = "Recherches"
                url = "/research/"
                weight = 6       


[taxonomies]
    tag = "tags"
    medium = "media"
    creator = "creators"
    series = "series"
    franchise = "franchise"
    title = "titles"
    rating = "ratings"
    type = "types"
    source = "sources"
    outlet = "outlets"
    co-author = "co-authors"
    project = "projects"
    topic = "topics"
    publication_type = "publication_types"
    method = "methods"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Spencer Greenhalgh"
  text_color = ""
  author = ""
  favicon = "/SPG_4_circle_small.png"
  site_logo = "/SPG_4_circle_small.png"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = ""
  recent_posts_number = 2
  
  [params.ananke.social]
  
    [ananke.social.networks.scholar]
                slug = "scholar"
                label = "Google Scholar"
                icon = "graduation-cap"
                profile = false
                share = false
                
     [ananke.social.networks.newsletter]
                slug = "newsletter"
                label = "newsletter"
                icon = "newspaper"
                profile = false
                share = false
                
     [ananke.social.networks.microblog]
                slug = "microblog"
                label = "Micro.blog"
                icon = "microblog"
                profile = false
                share = false

  
    [params.ananke.social.follow]
        new_window_icon = true
        networks = [
        "email",
        "newsletter",
        "rss",
        "scholar",
        "mastodon",
        "bluesky",
        "microblog"
        ]
        
        [params.ananke.social.bluesky]
            profilelink = "https://bsky.app/profile/spencergreenhalgh.com"
            
        [params.ananke.social.email]
            profilelink = "mailto:spencer.greenhalgh@posteo.net"

        [params.ananke.social.rss]
            profilelink = "https://spencergreenhalgh.com/index.xml"
            
        [params.ananke.social.mastodon]
            profilelink = "https://mastodon.spencergreenhalgh.com/public/local"
            
        [params.ananke.social.scholar]
            profilelink = "https://scholar.google.com/citations?user=o3JQjpcAAAAJ&hl=en&oi=ao"
            
                            
        [params.ananke.social.newsletter]
            profilelink = "https://scholar.google.com/citations?user=o3JQjpcAAAAJ&hl=en&oi=ao"
            
           
            
    

  