[build.environment]
DART_SASS_VERSION = "1.97.1"
GO_VERSION = "1.25.5"
HUGO_VERSION = "0.153.2"
NODE_VERSION = "24.12.0"
TZ = "Europe/Oslo"

[build]
publish = "public"
command = """\
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}"
  """