[build]
publish = "./exampleSite/public/"
command = "npm run deploy"
[build.environment]
DART_SASS_VERSION = "1.93.2"
HUGO_VERSION = "0.152.0"
HUGO_ENV = "production"
GO_VERSION = "1.23"
NODE_ENV = "development"
